[package]
name = "lpc111x-pac"
edition = "2021"
version = "0.1.0"

[dependencies]
cortex-m = "0.7"
cortex-m-rt = { version = "0.7", optional = true }
vcell = "0.1"
critical-section = { version = "1.0", optional = true }

[features]
rt = ["cortex-m-rt/device"]
